image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - maximedenes.vscoq

tasks:
  - command: >
      eval $(opam env) && bash README.md && (./coqide Tactics.v &)

ports:
  # vnc port
  - port: 6080
    onOpen: open-browser
